version: '3.3'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - eventsdb

  eventsdb:
    container_name: eventsdb
    image: mongo:6.0
    volumes:
      - ./etc/sample_db:/docker-entrypoint-initdb.d:ro
    ports:
      - 27017:27017
