// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.2
// source: event.proto

package event_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EventV1Client is the client API for EventV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventV1Client interface {
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error)
}

type eventV1Client struct {
	cc grpc.ClientConnInterface
}

func NewEventV1Client(cc grpc.ClientConnInterface) EventV1Client {
	return &eventV1Client{cc}
}

func (c *eventV1Client) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*CreateResponse, error) {
	out := new(CreateResponse)
	err := c.cc.Invoke(ctx, "/event_v1.EventV1/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EventV1Server is the server API for EventV1 service.
// All implementations must embed UnimplementedEventV1Server
// for forward compatibility
type EventV1Server interface {
	Create(context.Context, *CreateRequest) (*CreateResponse, error)
	mustEmbedUnimplementedEventV1Server()
}

// UnimplementedEventV1Server must be embedded to have forward compatible implementations.
type UnimplementedEventV1Server struct {
}

func (UnimplementedEventV1Server) Create(context.Context, *CreateRequest) (*CreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEventV1Server) mustEmbedUnimplementedEventV1Server() {}

// UnsafeEventV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventV1Server will
// result in compilation errors.
type UnsafeEventV1Server interface {
	mustEmbedUnimplementedEventV1Server()
}

func RegisterEventV1Server(s grpc.ServiceRegistrar, srv EventV1Server) {
	s.RegisterService(&EventV1_ServiceDesc, srv)
}

func _EventV1_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EventV1Server).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/event_v1.EventV1/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EventV1Server).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EventV1_ServiceDesc is the grpc.ServiceDesc for EventV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "event_v1.EventV1",
	HandlerType: (*EventV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EventV1_Create_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "event.proto",
}
